################################################################
################################################################
####
#### This makefile is part of the source of 
#### "Parallel Computing for Science and Engineering"
#### by Victor Eijkhout, copyright 2013/4
####
#### This is the makefile for the examples/mpi/p
####
################################################################
################################################################

info ::

info ::
	@echo "make regression"
regression :
	@echo "we will do regression later"

info ::
	@echo "make listsources"
SOURCES = mpi.py hello.py pingpong.py scipingpong.py bcast.py buffertoosmall.py buffertoolarge.py \
  gatherv.py allreduce.py getfence.py
listsources :
	@echo ${SOURCES}

info ::
	@echo "make clean"
clean ::
	@/bin/rm -rf *~
