#!/bin/bash

################################################################
####
#### This script is part of `Parallel Programming in MPI and OpenMP'
#### by Victor Eijkhout, copyright 2013-7
#### eijkhout@tacc.utexas.edu
####
#### catchout : auxiliary file for catching the output of one MPI rank
####
################################################################

if [ $# -lt 1 ] ; then
  echo "Usage: $0 [-p runner] program"
  exit 1;
fi
if [ $1 == "-p" ] ; then
    shift
    PYTHON=1
    RUNNER=$1
    shift
else
    PYTHON=0
fi
if [ $# -lt 1 ] ; then
  echo "Usage: $0 [-p runner] program"
  exit 1;
fi

if [ $PYTHON -eq 1 ] ; then
    $RUNNER ./$1.py > $1.out${PMI_RANK} 2>&1
else
    ./$1 > $1.out${PMI_RANK} 2>&1
fi
