################################################################
################################################################
####
#### This makefile is part of the source of 
#### "Parallel Programming in MPI and OpenMP"
#### by Victor Eijkhout, copyright 2013-8
####
#### Makefile for course support
####
################################################################
################################################################

info::

info ::
	@echo "make clean"
.PHONY: clean
clean ::
	@/bin/rm -f *~ *.{aux,blg,idx,ilg,ind,log,nav,out,snm,toc,vrb} *.cut
	@/bin/rm -f hostfile* *.xml
